### ISSUE TITLE
Calcolo guadagno

### ISSUE THREAD

**Issue by Pe13** [A-lida/lab_elettronica#14]
## Per quanto riguarda il calcolo del guadagno, non credo abbia senso fare la media come dicevamo perché facendo il grafico viene questo:

![immagine](https://github.com/user-attachments/assets/0ce9dd24-1425-4c30-b9da-837fa0c65efb)

## Ed ha senso dato che come abbiamo visto ieri, le caratteristiche fanno così:
![immagine](https://github.com/user-attachments/assets/11eca218-3933-4b0e-8073-9ae0c5faf679)

## Quindi direi che possiamo fare come chiede lei nella guida alla prova di lab e mettere il guadagno per un potenziale a scelta
@A-lida

**Comment by Pe13** [comment]
Obbiettivamente già che abbiamo fatto il grafico possiamo metterlo

**Comment by A-lida** [comment]
Magari il grafico lo mettiamo in appendice

**Comment by Pe13** [comment]
> Magari il grafico lo mettiamo in appendice

🙃

**Comment by A-lida** [comment]
beh ma la parte centrale non va bene? secondo me si

**Comment by Pe13** [comment]
La parte centrale cosa?
Avevamo detto che volevamo fare una media, ma ha senso solo se è costante, e palesemente non lo è

**Comment by A-lida** [comment]
non mi è chiaro cosa tu abbia mediato

**Comment by Pe13** [comment]
Completato in 8cbb11ff
